name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - name: Install GoogleTest dependencies
      run: sudo apt-get install libgtest-dev

    - name: Generate build files
      run: cmake -S . -B build -G Ninja

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
