name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh build Debug

    - name: Run tests
      run: |
        cd build/Debug
        ctest --output-on-failure
